### ISSUE TITLE
multipleServers 

### ISSUE THREAD

**Issue by mrjove** [Azumi67/UDP2RAW_FEC#1]
درود
من چندین بار تونل رو نصب کردم و اموزش های شمارو خوندم اما متوجه نشدم که اگر من روی سرور خارج خودم چندین پورت از کانفیگ های وایرگارد داشته باشم چطور میتونم همه اون پورت هارو با این روش تونل کنم به سرور ایرانم و در نهایت ادرس تونل من با کدوم پورت  میشه؟
من در تونل تعداد کانفیگ هارو 2 میزنم اما بازم ازم اطلاعات یک کانفیگ رو میگیره 
 ممنون میشم راهنمایی کنید

**Comment by Azumi67** [comment]
سلام باشه نگاه میکنم و بعدا آپدیت میدم

**Comment by Azumi67** [comment]
اپدیت شد

**Comment by mrjove** [comment]
با سلام و درود 

امکانش یک رنج پورت برای تونل اختصاص داد؟ به عنوان مثال 8000 تا  9000 یا محدودیتی در تعداد کانفیگ ها وجود دارد؟

اگر چنین شرایطی وجود ندارد امکانش هست اضافه شود؟

**Comment by Azumi67** [comment]
سلام. برای این تانل امکان پورت رنج نیست چون خود برنامه پشتیبانی نمیکند.
